sudo: required

language: csharp

branches:
  only:
  - master

services:
  - docker

script:
    - docker build -t webapp:test -f ./dockerfile/test .
    - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test

 after_success:
    - docker build -t webapp:release -f ./dockerfile/release .
    - docker tag webapp:release fredlab7/webapp:release
    - docker login -u=fredlab7 -p=$DOCKER_HUB_PASSWD
    - docker push fredlab7/webapp:latest

